data:
    name: 'fingernail_minutiae'
    labels: outputs/fingernail-minutiae_apoint_label  # Complete with your export labels
    cache_in_memory: false
    validation_size: 128
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'fingernail_minutiae'
    batch_size: 30
    eval_batch_size: 32
    learning_rate: 0.001
    detection_threshold: 0.001 # 0.015
    nms: 4
    p_loss: 1
    c_loss: 0.5
    a_loss: 0.02
    # top_k: 300
train_iter: 18000000
validation_interval: 1000
